Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: ComputeNest Production Deployment
+name: ComputeNest Build-Service Deployment
 
 on:
   workflow_dispatch:
@@ -7,13 +7,13 @@ on:
       - main
 
 jobs:
-  Deploy-Production:
+  Build-Service:
     runs-on: ubuntu-latest
     environment: default  # 使用环境 default
-    env: 
+    env:
       AK_ID: ${{ secrets.AK_ID }}
       AK_SECRET: ${{ secrets.AK_SECRET }}
-      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
+      SERVICE_NAME: 我试试action
       REGION_ID: ${{ secrets.REGION_ID || 'cn-hangzhou' }}
     steps:
       - uses: actions/checkout@v2
@@ -22,7 +22,7 @@ jobs:
         run: |
           if [ ! -d ".computenest" ]; then
             echo "Error: .computenest directory not found. Please import your service from the ComputeNest console."
-            echo "Guide here: https://computenest.console.aliyun.com/service/create/cn-hangzhou"
+            echo "Guide here: https://computenest.console.aliyun.com/service/create/default"
             exit 1
           fi
 
@@ -34,29 +34,32 @@ jobs:
       - name: Install ComputeNest CLI
         run: pip install computenest-cli
 
-      - name: Validate REGION_ID
-        run: |
-          if [[ "$REGION_ID" != "ap-southeast-1" && "$REGION_ID" != "cn-hangzhou" ]]; then
-            echo "Error: Invalid REGION_ID value. Only 'ap-southeast-1' and 'cn-hangzhou' are allowed."
-            exit 1
-          fi
-
       - name: Login to ComputeNest CLI
         run: |
           computenest-cli login --access_key_id "$AK_ID" --access_key_secret "$AK_SECRET"
 
-      - name: Import Service using ComputeNest CLI
+      - name: Build draft compute nest service
         run: |
-          params=()
-          if [[ ! -z "$SERVICE_NAME" ]]; then
-            params+=(--service_name "$SERVICE_NAME")
-            params+=(--region_id "$REGION_ID")
-          else
-            echo "Error: SERVICE_NAME is not set."
+          
+          if [[ "$REGION_ID" != "ap-southeast-1" && "$REGION_ID" != "cn-hangzhou" ]]; then
+            echo "Error: Invalid REGION_ID value. Only 'ap-southeast-1' and 'cn-hangzhou' are allowed."
             exit 1
           fi
-
+          
+          params=()
+  
+          if [[ ! -z "$SERVICE_NAME" ]]; then
+            params+=(--service_name "$SERVICE_NAME")
+            else
+          echo "Error: SERVICE_NAME is not set."
+            exit 1
+          fi
+            
+          if [[ ! -z "$REGION_ID" ]]; then
+            params+=(--region_id "$REGION_ID")
+          fi
+          
           computenest-cli import "${params[@]}" || { echo 'Import failed'; exit 1; }
 
       - name: Output Result
-        run: echo "Deployment completed."
+        run: echo "Build-Service completed."
